#!/bin/sh

ENABLED=yes

DESC="NDP Proxy Daemon"
PROCS="ndppd"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "PID_FILE"
}

PRECMD="pre_cmd"
ARGS="-p $PID_FILE -d"
PREARGS=""

. /opt/etc/init.d/rc.func
