#!/bin/sh

ENABLED=yes

DESC="BIRD Internet Routing Daemon (v2)"
PROCS="bird"
PROG="/opt/sbin/$PROCS"

PID_FILE="/opt/var/run/$PROCS.pid"

pre_cmd() {
  rm -f "PID_FILE"
}

PRECMD="pre_cmd"
ARGS="-f -c /opt/etc/$PROCS.conf -P $PID_FILE"
PREARGS=""

. /opt/etc/init.d/rc.func
